# -*- coding: utf-8 -*-
"""study4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186FTn-snzQoPyI1fjCHMetWZs_qNLMJt

#Tuple
## Odered collection of items()
## one main diffrence with is tuple is immutable
var_name = list[[stu:()],[stu2:()]...]
"""

# Create a truple
student=(101,"Pushpa","CSE",8.3)
print(student)
#tuple using index
print(student[0])
#we are using negative index
print(student[-1])
# to find the length of the tuple
print(len(student))
# Slicing Method
print(student[1:3])
print(student[:4])
print(student[2:])

# Indentity verify by single element
std=("Apple")
print(std)
print(type(std))
# Not tuple
std=("Apple",)
print(std)
print(type(std))

# Coount Function
marks= (10,20,30,20)
print("time of occurence:",marks.count(20))

sd=("Python",
    "SQL",
    "HTML",
    "CSS")
print("Python" in sd)
print("dsa" in sd)

"""#SET
 ##-> Unordered collection of item
 ## -> mutable
 ## -> Allow  the diffence data types
 ## -> it does'nt support index
 ## -> it gives output with unique (no Duplicate)
"""

# Symbol for set {}
# Create a set with similar iteam
marks ={ 75,20,99,99,20,10,100,75}
print(marks)

#Create a empty set
a={}
a=set()
# Check its type
print(type(a))

# Update set
std= { "pk","Dj","RK"}
y={"ram","Shyam","Priya"}

std.update(y)
print(std)
# Remove item
std.remove("pk")
print(std)

# if element is not present in set then you used remove method by element you can show error
# if you can used discard method by missing element you does'nt show error
std = { "karsm","Gk","DK"}
std.discard("lala")
print(std)

# clear method by set
student = {"amit",
           "kalli",
           "Jugander"}

student.clear()
print(student)

#set operation
python_student = {"a","b","c","d"}
java_student = {"a","e","f","g","h"}

# for union operation by using set
result= python_student.union(java_student)
print("Union Operater : ",result)

# for interset operster by usng set
resukt_interset = python_student.intersection(java_student)
print("Intersection operater: ",resukt_interset)

# To find difference with two set
res_id = python_student.difference(java_student)
print(res_id)

# convert elist to set
stud = [101,102,120,150,160]
unique_id= set(stud)
print(unique_id)
# convert set to list
stud=list(unique_id)
print(stud)